### ISSUE TITLE
[Fabric] Crash when placing down TV

### ISSUE THREAD

**Issue by t-hermanns** [NGoedix/VideoPlayer#45]
Whenever i place down a TV in singleplayer or open a world with a TV in it, the game crashes

VideoPlayer-2.6.1-FABRIC-1.20.X
WaterMedia 2.0.31 (also tested with 2.0.27-beta, 2.0.25, 2.0.24 and 2.0.10)
Fabric 0.83.0+1.20

[crash-2024-04-18_22.46.26-client.txt](https://github.com/NGoedix/VideoPlayer/files/15030639/crash-2024-04-18_22.46.26-client.txt)

**Comment by t-hermanns** [comment]
seems to be some kind of recursive call loop of these three functions
```
at com.github.NGoedix.videoplayer.util.displayers.VideoDisplayer.createVideoDisplay(VideoDisplayer.java:45)
at com.github.NGoedix.videoplayer.util.cache.TextureCache.createDisplay(TextureCache.java:59)
at com.github.NGoedix.videoplayer.util.cache.TextureCache.createDisplay(TextureCache.java:54)
```

**Comment by this-dude-codes** [comment]
it happens on latest forge version too
1.9.2 Forge
