### ISSUE TITLE
Dont working video player in fabric 1.20.1

### ISSUE THREAD

**Issue by SASKERR** [NGoedix/VideoPlayer#68]
java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'videoplayer' at 'com.github.NGoedix.videoplayer.client.ClientHandler'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53)
	at knot//net.minecraft.class_310.<init>(class_310.java:458)
	at knot//net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: me/srrapero720/watermedia/core/tools/JarTool
	at knot//com.github.NGoedix.videoplayer.client.ClientHandler.onInitializeClient(ClientHandler.java:65)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.ClassNotFoundException: me.srrapero720.watermedia.core.tools.JarTool
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 8 more
thats the error of the mod
:(

**Comment by TheSystemGuy1337** [comment]
This software is abandonware; they don't even work on it and issues have been going unread. And they have been blanketing versions that they support. This mod really only properly supports 1.18.2

**Comment by NGoedix** [comment]
Hi @TheSystemGuy1337!

I am currently updating the mod but I don't have so much time to do it so don't say that is "abandonware" and if you want precise news join to the discord channel or you can do any PR updating/improving it.

**Comment by Thexiaoyuqaq** [comment]
https://github.com/Thexiaoyuqaq/VideoPlayer-fix
